name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  _2018:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd Y2018 && swift build -v
    - name: Run tests
      run: cd Y2018 && swift test -v

  _2019:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd Y2019 && swift build -v
    - name: Run tests
      run: cd Y2019 && swift test -v

  _2020:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd Y2020 && swift build -v
    - name: Run tests
      run: cd Y2020 && swift test -v

  _2021:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd Y2021 && swift build -v
    - name: Run tests
      run: cd Y2021 && swift test -v

